### ISSUE TITLE
Incorrect JWS used on 15

### ISSUE THREAD

**Issue by vivianaranha** [dvci/health-cards-walkthrough#3]
I see that you get the scannedJWS on line 14 but when you try to verify - you use jws which was defined in line 7 which is the input - Thats why I see both the input and output is same - I tried to use the scannedJWS and it gives me error Error: no key found

**Comment by radamson** [comment]
You can visually see that the JWS are the same so validating the original jws vs. the scannedjws shouldn't make an actual difference. That being said this is still a mistake and the code should be validating the scannedJWS here.

I opened a PR with a fix in #6, but I'm not seeing the error you are reporting. Are you restarting the kernel and running all steps at once or running each one by one?
