### ISSUE TITLE
V22 should be an upper bound on symbol size

### ISSUE THREAD

**Issue by jmandel** [dvci/health-cards-walkthrough#4]
Just got an email from a team implementing SMART Health Cards that got tripped up by this example:

    QRCode.toString(segments,{type: 'svg', errorCorrectionLevel: 'low', version: 22 }).then(function(result){

This code will *always* use a `V22` symbol even if the actual data could fit into something smaller. Instead, we should allow the `qrcode` library to choose a smaller symbol size if one fits. We could drop the `version: 22` argument, and possibly add back a check/assertion that the generated code fits in V22 (there's no obvious way to accomplish this with library we're using, but we could always 1) generate a V22 QRcode in a try block to ensure it doesn't blow up, and then 2) if successful, generate again, without a `version` parameter (which indicates we'll have a  V <= 22 code).

**Comment by jhcao23** [comment]
Hi @jmandel, if not `version` specified, is [node-qrcode](https://github.com/soldair/node-qrcode) using lower version or v40 by default?

**Comment by jmandel** [comment]
The default is to pick the smallest version that will fit

**Comment by radamson** [comment]
Added chunking code and removed `version: 22` argument so the QR code should always be version 22 or less in https://github.com/dvci/health-cards-walkthrough/pull/8

@jmandel if this needs further discussion please re-open this issue!
